backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "static/_content/about.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - label: "Home Page"
        name: "home"
        file: "static/_content/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Button Text, name: buttonText, widget: string }
              - {
                  label: Button Link,
                  name: buttonLink,
                  widget: select,
                  options: ["highschool", "coaches", "about", "home"],
                }
      - label: "Coaches Page"
        name: "coaches"
        file: "static/_content/coaches.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: Coaches
            name: coaches
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Position,
                  name: position,
                  widget: string,
                  required: false,
                }
              - { label: Bio, name: bio, widget: markdown }
              - { label: Photo, name: photo, widget: image, required: false }
      - label: "High School Program Page"
        name: "highschool"
        file: "static/_content/highschool.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown, required: false }
