backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/images # Where media files will be stored in the repo
public_folder: /images # The src attribute uploaded media will begin with

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "static/_content/about.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - label: "Home Page"
        name: "home"
        file: "static/_content/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Seo Title, name: seoTitle, widget: string }
          - {
              label: Sub Title,
              name: subTitle,
              widget: string,
              required: false,
            }
          - { label: Programming Title, name: cardTitle, widget: string }
          - label: "Image Slider"
            name: "images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: true
          - label: Program Cards
            name: cards
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: string }
              - { label: Age Group, name: ageGroup, widget: string }
              - { label: Date Range, name: date, widget: string }
              - label: Links
                name: links
                widget: list
                fields:
                  - { label: Link Text, name: text, widget: string }
                  - { label: Link To, name: link, widget: string }
                  - {
                      label: Open In New Tab,
                      name: newTab,
                      widget: boolean,
                      default: false,
                    }
                  - {
                      label: Link Disabled,
                      name: disabled,
                      widget: boolean,
                      default: false,
                    }
      - label: "Blog"
        name: "blog"
        file: "static/_content/posts.json"
        fields:
          - { label: Blog Title, name: title, widget: string }
          - label: Posts
            name: posts
            widget: list
            fields:
              - { label: Post Title, name: title, widget: string }
              - { label: Post Slug, name: slug, widget: string }
              - { label: Post Content, name: content, widget: markdown }
      - label: "Juniors"
        name: "juniors"
        file: "static/_content/juniors.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Title, name: seoTitle, widget: string }
          - { label: Main Content, name: content, widget: string }
          - label: Programs
            name: programs
            widget: list
            fields:
              - { label: "Program Name", name: "tabName", widget: string }
              - { label: "Program Content", name: "content", widget: markdown }
              - { label: "Airtable Link", name: "airtableLink", widget: string }
      - label: "Coaches Page"
        name: "coaches"
        file: "static/_content/coaches.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: Coaches
            name: coaches
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Position,
                  name: position,
                  widget: string,
                  required: false,
                }
              - { label: Bio, name: bio, widget: markdown, required: false }
              - { label: Photo, name: photo, widget: image, required: false }
      - label: "High School Program Page"
        name: "highschool"
        file: "static/_content/highschool.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown, required: false }
